// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7RNd4GZo-lyd0s_MeXAgqkcSWWrslag',
    appId: '1:255595089158:web:b8c7e3d5b28b8213f62287',
    messagingSenderId: '255595089158',
    projectId: 'your-days-4aad4',
    authDomain: 'your-days-4aad4.firebaseapp.com',
    storageBucket: 'your-days-4aad4.firebasestorage.app',
    measurementId: 'G-CL2631MGC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPaBMT190aknlewXycIXK95K5LdjPaBew',
    appId: '1:255595089158:android:955746c5acd6f642f62287',
    messagingSenderId: '255595089158',
    projectId: 'your-days-4aad4',
    storageBucket: 'your-days-4aad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxyh5MFDRM3k3IO2pwwGdnoaSZ_7rNdw',
    appId: '1:255595089158:ios:7f6ceb6a95e6b3f2f62287',
    messagingSenderId: '255595089158',
    projectId: 'your-days-4aad4',
    storageBucket: 'your-days-4aad4.firebasestorage.app',
    iosBundleId: 'com.example.yourDays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxyh5MFDRM3k3IO2pwwGdnoaSZ_7rNdw',
    appId: '1:255595089158:ios:7f6ceb6a95e6b3f2f62287',
    messagingSenderId: '255595089158',
    projectId: 'your-days-4aad4',
    storageBucket: 'your-days-4aad4.firebasestorage.app',
    iosBundleId: 'com.example.yourDays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl7RNd4GZo-lyd0s_MeXAgqkcSWWrslag',
    appId: '1:255595089158:web:6e8b0d67b4eac3eef62287',
    messagingSenderId: '255595089158',
    projectId: 'your-days-4aad4',
    authDomain: 'your-days-4aad4.firebaseapp.com',
    storageBucket: 'your-days-4aad4.firebasestorage.app',
    measurementId: 'G-CXSWB1F3TW',
  );
}
